### PR TITLE
Lepnikov ClassWork 19.03.2021

### PR DESCRIPTION
**Pull request by norsulfazol**

### CODE REVIEW

**Review by MikitaTsiarentsyeu — CHANGES_REQUESTED** [review]
image

So, lets talk about validation logic based on the exceptions mechanism =)

**Comment by norsulfazol** [comment]
Nothing better came to mind than adding one more check. Is it correct?
изображение

**Comment by MikitaTsiarentsyeu** [comment]
It's absolutely correct in this particular case, but I would encourage you to not hesitate of using empty except statement to catch all potential problems with the input. For example, in this case we know that the input is correct only in one case - if it's a number, ergo when float conversion is done without errors. So we can just catch any error and notify user that the input is incorrect.

**Comment by norsulfazol** [comment]
I agree with you, it is easier to make greater use of "naked" except (without specific exception classes) for "trapping" of all exceptions. But in this particular case, such a construction:
изображение
"skips" the input of the values NaN and Infinity because:
изображение
The error "NameError: name 'nan' is not defined" occurs not at the validation stage, but later when trying to calculate in the eval().
изображение

We need to discuss this issue sometime ...

**Comment by norsulfazol** [comment]
And more: PEP 8: E722 do not use bare 'except' ;)

**Comment by MikitaTsiarentsyeu** [comment]
Oh, those hypocrites are just messing with us, nobody would test production code so thoroughly to claim that they know every potential exception that could occur. 
As for our case - you're right, I've catch you with the nan value and then didn't take into account that it's a valid value for conversion. Your approach with 2 except is correct, but I would still use empty except, and add simple check for both values in question, and raise my own exception in case this is one of those cases. Nevertheless it's kind of question of personal preferences, and I'm not pushing you to take my side, especially when you are aware of PEP =)

**Pull request merged**
