### PR TITLE
Stanislav

### PR DESCRIPTION
**Pull request by StanislavBrizgalov**
Домашнее задание №3.

### CODE REVIEW

**Review by MikitaTsiarentsyeu — CHANGES_REQUESTED** [review]
image
it's really inconsistent formatting

image
fix this error please

**Comment by StanislavBrizgalov** [comment]
посмотрите пожалуйста, 3 задание.

**Comment by StanislavBrizgalov** [comment]
Напутал конечно )

**Review by MikitaTsiarentsyeu — APPROVED** [review]
Nice job, it's a completely correct program, although I would like to see some string formatting instead of manual pre-describing of all the values. Your score is 8.0.

**Pull request merged**
